apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabel }}-svc
  labels:
    name: {{ .Values.appLabel }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    app: {{ .Values.appLabel }}
