apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  labels:
    app: myapp-backend
  namespace: myapp-backend
spec:
  selector:
    matchLabels:
      app: myapp-backend
  template:
    spec:
      containers:
        - name: myapp-backend
          image: aiacraa22.azurecr.io/samples/nginx:latest