apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-may-aks
  labels:
    app: meetup-may-aks
  namespace: namespace-workflow-1685161792398
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-may-aks
  template:
    metadata:
      labels:
        app: meetup-may-aks
    spec:
      containers:
        - name: meetup-may-aks
          image: aiacraa22.azurecr.io/image-workflow-1685161792398:latest
          ports:
            - containerPort: 5000