apiVersion: v1
kind: Service
metadata:
  name: meetup-may-aks
  namespace: namespace-workflow-1685161792398
spec:
  type: LoadBalancer
  selector:
    app: meetup-may-aks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000