apiVersion: v1
kind: Service
metadata:
  name: myapp-backend
  namespace: myapp-backend
spec:
  type: LoadBalancer
  selector:
    app: myapp-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080